name: CI

on:
  push:
    branches: [ $default-branch, github_ci_test ]
  pull_request:
    branches: [ $default-branch, github_ci_test ]

jobs:
  fuzzer:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    env:
      CC: ${{ matrix.compiler }}
      CC_FOR_BUILD: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Fuzzer
        run: GIT_REF=$GITHUB_REF ./ci/ossfuzz.sh
