name: CI

on:
  push:
    branches: [ master, github_ci ]
  pull_request:
    branches: [ master, github_ci ]

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        # MSVC 2015, 2017, and 2019, respectively
        toolset: [v120, v140, v141, v142]
        arch: [Win32, x64]
        crypto_backend: [OpenSSL, WinCNG]
        build_shared_libs: [OFF, ON]
        configuration: [Release]
    env:
      TOOLSET: ${{ matrix.toolset }}
      BUILD_ARCH: ${{ matrix.arch }}
      CRYPTO_BACKEND: ${{ matrix.crypto_backend }}
      BUILD_SHARED_LIBS: ${{ matrix.build_shared_libs }}
      CONFIGURATION: ${{ matrix.configuration }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache vcpkg installs
        uses: actions/cache@v1
        with:
          path: C:\vcpkg\installed
          key: ${{ runner.os }}-vcpkg
      - name: Install OpenSSL
        if: ${{ matrix.crypto_backend == 'OpenSSL' }}
        run: |
          if ($env:BUILD_ARCH -eq "Win32") { $ARCH = "x86" } else { $ARCH = "x64" }
          vcpkg install openssl:${ARCH}-windows
      - name: Install Visual Studio 2013
        if: ${{ matrix.toolset == 'v120' }}
        run: choco install visualstudiocommunity2013 --install-arguments="'/l*v ${{ github.workspace }}\VisualStudioCommunity2013_msi_install.log'"
      - name: Step To run on failure
        if: ${{ matrix.toolset == 'v120' && failure() }}
        run: cat ${{ github.workspace }}\VisualStudioCommunity2013_msi_install.log
      - name: Generate CMake Project
        run: |
          mkdir bin
          cd bin
          cmake -G "Visual Studio 16 2019" -A $env:BUILD_ARCH -T $env:TOOLSET -DCRYPTO_BACKEND="$env:CRYPTO_BACKEND" -DBUILD_SHARED_LIBS="$env:BUILD_SHARED_LIBS" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" ..
      - name: Build CMake Project
        working-directory: ./bin
        run: cmake --build . --config $env:CONFIGURATION
